const $=id=>document.getElementById(id);const file=$('file'),analysis=$('analysis'),preview=$('preview'),message=$('message'),summary=$('summary'),sheets=$('sheets'),mapping=$('mapping'),table=$('table'),download=$('download');
const ALIASES={institucion:['institucion','entidad','organismo','unidad contratante'],licitacion:['licitacion','llamado','contratacion','contratación'],lote:['lote','numero lote','número lote'],grupo:['grupo','numero grupo','número grupo'],item:['item','ítem','numero item','número item','nro item'],codigo:['codigo','código','codigo catalogo','código catálogo','codigo de producto','código de producto','catalogo','catálogo'],grupo_descripcion:['grupo descripcion','grupo descripción','lote descripcion','lote descripción'],descripcion:['descripcion','descripción','detalle','nombre del producto','producto','objeto'],cantidad:['cantidad','cant'],contrato_abierto:['contrato abierto'],abastecimiento:['abastecimiento simultaneo','abastecimiento simultáneo'],tipo_contrato:['tipo contrato abierto'],cantidad_adjudicada:['cantidad adjudicada'],porcentaje:['porcentaje de distribucion','porcentaje de distribución'],precio_unitario:['precio unitario','precio unitario iva incluido','precio unitario adjudicado'],adjudicado:['adjudicado','proveedor','adjudicatario','empresa'],atributo:['atributo','atributos','caracteristica','característica'],atributo_valor:['descripcion atributo','descripción atributo','valor atributo']};
const DNCP_HEADERS=['"Número Lote"','Número Grupo','Número Item','Código de Producto','Grupo Descripción','Nombre del Producto','Cantidad','Contrato Abierto','Abastecimiento Simultáneo','Tipo Contrato Abierto','Cantidad Adjudicada','Porcentaje de Distribución','Precio Unitario Adjudicado','Atributo','Descripción Atributo'];
let wb=null,rows=[],meta={};
function norm(v){return String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ')}function esc(v){return String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]))}
function headerScore(row){let score=0;const vals=row.map(norm);for(const a of Object.values(ALIASES))if(vals.some(v=>a.some(x=>v===norm(x)||v.includes(norm(x)))))score++;return score}
function findHeader(data){let best={index:0,score:-1,headers:[]};data.slice(0,80).forEach((r,i)=>{const s=headerScore(r);if(s>best.score)best={index:i,score:s,headers:r.map(v=>String(v??'').trim())}});return best}
function fieldIndex(headers,field){const a=ALIASES[field]||[];for(let i=0;i<headers.length;i++){const h=norm(headers[i]);if(a.some(x=>h===norm(x)||h.includes(norm(x))))return i}return -1}
function findValue(data,labels){for(const r of data.slice(0,50)){for(let c=0;c<Math.min(r.length,5);c++){const s=norm(r[c]);if(labels.some(l=>s.includes(norm(l))))return String(r[c]??'').split(':').slice(1).join(':').trim()||String(r[c+1]??'').trim()}}return ''}
function analyze(){rows=[];meta={};sheets.innerHTML='';mapping.innerHTML='';const map={};wb.SheetNames.forEach(name=>{const data=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:''});meta.licitacion ||= findValue(data,['licitacion','llamado']);meta.institucion ||= findValue(data,['institucion','entidad']);meta.proveedor ||= findValue(data,['adjudicado','proveedor','adjudicatario']);const h=findHeader(data);sheets.insertAdjacentHTML('beforeend',`<div class="sheet"><b>${esc(name)}</b> — encabezado probable: fila ${h.index+1}; campos reconocidos: ${h.score}</div>`);for(const f of Object.keys(ALIASES)){const i=fieldIndex(h.headers,f);if(i>=0)map[f]=h.headers[i]}let lastLot='',lastGroup='',lastGroupDesc='';for(let r=h.index+1;r<data.length;r++){const raw=data[r];if(!raw.some(v=>String(v??'').trim()))continue;const obj={sheet:name};for(const f of Object.keys(ALIASES)){const i=fieldIndex(h.headers,f);obj[f]=i>=0?(raw[i]??''):''}if(obj.lote)lastLot=obj.lote;if(obj.grupo)lastGroup=obj.grupo;if(obj.grupo_descripcion)lastGroupDesc=obj.grupo_descripcion;obj.lote ||= lastLot;obj.grupo ||= lastGroup;obj.grupo_descripcion ||= lastGroupDesc;if(Object.values(obj).some(v=>String(v??'').trim()))rows.push(obj)}});Object.entries(map).forEach(([k,v])=>mapping.insertAdjacentHTML('beforeend',`<div class="mapitem"><code>${esc(k)}</code> ← ${esc(v)}</div>`));summary.innerHTML=`<p class="ok">Hojas: <b>${wb.SheetNames.length}</b> | registros detectados: <b>${rows.length}</b></p>`;render()}
function render(){const cols=['lote','grupo','item','codigo','grupo_descripcion','descripcion','cantidad','contrato_abierto','abastecimiento','tipo_contrato','cantidad_adjudicada','porcentaje','precio_unitario'];table.innerHTML='<thead><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr></thead><tbody>'+rows.slice(0,150).map(r=>'<tr>'+cols.map(c=>`<td>${esc(r[c])}</td>`).join('')+'</tr>').join('')+'</tbody>';preview.classList.remove('hidden');download.disabled=!rows.length}
function csvCell(v){const s=String(v??'');return /[";\r\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function encodeWindows1252(text){const special={'€':0x80,'‚':0x82,'ƒ':0x83,'„':0x84,'…':0x85,'†':0x86,'‡':0x87,'ˆ':0x88,'‰':0x89,'Š':0x8a,'‹':0x8b,'Œ':0x8c,'Ž':0x8e,'‘':0x91,'’':0x92,'“':0x93,'”':0x94,'•':0x95,'–':0x96,'—':0x97,'˜':0x98,'™':0x99,'š':0x9a,'›':0x9b,'œ':0x9c,'ž':0x9e,'Ÿ':0x9f};const bytes=new Uint8Array(text.length);let n=0;for(const ch of text){const cp=ch.codePointAt(0);if(cp<=0x7f)bytes[n++]=cp;else if(cp>=0xa0&&cp<=0xff)bytes[n++]=cp;else if(special[ch]!==undefined)bytes[n++]=special[ch];else throw new Error(`Carácter no representable en Windows-1252: ${ch}`)}return bytes.slice(0,n)}
function generate(){const out=[];out.push([`LICITACIÓN: ${meta.licitacion||''}`,...Array(14).fill('')]);out.push([`SISTEMA DE ADJUDICACIÓN: ${meta.sistema||'lote'}`,...Array(14).fill('')]);out.push([`PROVEEDOR: ${meta.proveedor||''}`,...Array(14).fill('')]);out.push(['OBSERVACIÓN: En caso de que una fila no sera cargada eliminar la fila y los atributos de la lista. ',...Array(14).fill('')]);out.push(Array(15).fill(''));out.push(DNCP_HEADERS);for(const r of rows){const hasMain=['item','codigo','descripcion','precio_unitario','cantidad'].some(k=>String(r[k]??'').trim());if(hasMain)out.push([r.lote,r.grupo,r.item,r.codigo,r.grupo_descripcion,r.descripcion,r.cantidad,r.contrato_abierto,r.abastecimiento,r.tipo_contrato,r.cantidad_adjudicada,r.porcentaje,r.precio_unitario,'','']);if(String(r.atributo??'').trim()||String(r.atributo_valor??'').trim())out.push(Array(13).fill('').concat([r.atributo,r.atributo_valor]))}const csv=out.map(r=>r.map(csvCell).join(';')).join('\r\n');const bytes=encodeWindows1252(csv);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([bytes],{type:'text/csv;charset=windows-1252'}));a.download='salida_dncp.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
file.addEventListener('change',async()=>{const f=file.files[0];if(!f)return;try{message.textContent='Analizando...';wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:false});analysis.classList.remove('hidden');analyze();message.textContent=`Archivo cargado: ${f.name}`}catch(e){message.textContent='Error: '+e.message}});download.addEventListener('click',generate);
