const $=id=>document.getElementById(id);const file=$('file'),analysis=$('analysis'),preview=$('preview'),message=$('message'),summary=$('summary'),sheets=$('sheets'),mapping=$('mapping'),table=$('table'),download=$('download');
const ALIASES={institucion:['institucion','entidad','organismo','unidad contratante'],licitacion:['licitacion','llamado','contratacion','contratación'],lote:['lote','lotes','grupo'],item:['item','ítem','nro item','numero de item','número de ítem'],codigo:['codigo','código','codigo catalogo','código catálogo','catalogo','catálogo'],descripcion:['descripcion','descripción','detalle','objeto'],cantidad:['cantidad','cant'],precio_unitario:['precio unitario','precio unitario iva incluido'],precio_total:['precio total','total','importe total'],adjudicado:['adjudicado','proveedor','adjudicatario','empresa'],atributos:['atributos','atributo'],caracteristicas:['caracteristicas','características']};
let wb=null,rows=[];
function norm(v){return String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ')}
function esc(v){return String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]))}
function headerScore(row){let score=0;const vals=row.map(norm);for(const a of Object.values(ALIASES))if(vals.some(v=>a.some(x=>v===norm(x)||v.includes(norm(x)))))score++;return score}
function findHeader(data){let best={index:0,score:-1,headers:[]};data.slice(0,60).forEach((r,i)=>{const s=headerScore(r);if(s>best.score)best={index:i,score:s,headers:r.map(v=>String(v??'').trim())}});return best}
function fieldIndex(headers,field){const a=ALIASES[field]||[];for(let i=0;i<headers.length;i++){const h=norm(headers[i]);if(a.some(x=>h===norm(x)||h.includes(norm(x))))return i}return -1}
function analyze(){rows=[];sheets.innerHTML='';mapping.innerHTML='';const map={};wb.SheetNames.forEach(name=>{const data=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:''});const h=findHeader(data);sheets.insertAdjacentHTML('beforeend',`<div class="sheet"><b>${esc(name)}</b> — encabezado probable: fila ${h.index+1}; campos reconocidos: ${h.score}</div>`);for(const f of Object.keys(ALIASES)){const i=fieldIndex(h.headers,f);if(i>=0){map[f]=h.headers[i];} }for(let r=h.index+1;r<data.length;r++){const raw=data[r];if(!raw.some(v=>String(v??'').trim()))continue;const obj={sheet:name};for(const f of Object.keys(ALIASES)){const i=fieldIndex(h.headers,f);obj[f]=i>=0?(raw[i]??''):''}if(Object.values(obj).some(v=>String(v??'').trim()))rows.push(obj)}});Object.entries(map).forEach(([k,v])=>mapping.insertAdjacentHTML('beforeend',`<div class="mapitem"><code>${esc(k)}</code> ← ${esc(v)}</div>`));summary.innerHTML=`<p class="ok">Hojas: <b>${wb.SheetNames.length}</b> | registros detectados: <b>${rows.length}</b></p>`;render();}
function render(){const cols=['sheet','lote','item','codigo','descripcion','cantidad','precio_unitario','precio_total','adjudicado'];table.innerHTML='<thead><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr></thead><tbody>'+rows.slice(0,150).map(r=>'<tr>'+cols.map(c=>`<td>${esc(r[c])}</td>`).join('')+'</tr>').join('')+'</tbody>';preview.classList.remove('hidden');download.disabled=!rows.length}
file.addEventListener('change',async()=>{const f=file.files[0];if(!f)return;try{message.textContent='Analizando...';wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:false});analysis.classList.remove('hidden');analyze();message.textContent=`Archivo cargado: ${f.name}`}catch(e){message.textContent='Error: '+e.message}});
download.addEventListener('click',()=>{const cols=['lote','item','codigo','descripcion','cantidad','precio_unitario','precio_total','adjudicado'];const out=[cols,...rows.map(r=>cols.map(c=>r[c]))];const csv='\ufeff'+out.map(r=>r.map(csvCell).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='salida_dncp.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});function csvCell(v){const s=String(v??'');return /[",\r\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
